### ISSUE TITLE
Bug when using FILTER_IMPORTANT_FINDINGS = True

### ISSUE THREAD

**Issue by yotam-bs** [r2c-CSE/semgrep_findings_to_csv_html_pdf_all_repos_filter_tag#4]
Setting "FILTER_IMPORTANT_FINDINGS = True" results in a runtime error "NameError: name 'project_name' is not defined".

Trace:
Traceback (most recent call last):
  File "C:\Temp\semgrep_findings_to_csv_html_pdf_all_repos_filter_tag.py", line 443, in <module>
    get_projects(slug_name, interesting_tag)
  File "C:\Temp\semgrep_findings_to_csv_html_pdf_all_repos_filter_tag.py", line 78, in get_projects
    get_findings_per_repo(slug_name, project_name)
  File "C:\Temp\semgrep_findings_to_csv_html_pdf_all_repos_filter_tag.py", line 119, in get_findings_per_repo
    logging.info("Filtering Important findings for requested project/repo: " + project_name)
                                                                               ^^^^^^^^^^^^
NameError: name 'project_name' is not defined

**Comment by yotam-bs** [comment]
Quick fix: Removing the 'project_name' reference from the logging.info line solves the issue.
logging.info("Filtering Important findings for requested project/repo: "_**,project_name**_)
